### ISSUE TITLE
Can't edit configuration for clixon-openconfig-example device

### ISSUE THREAD

**Issue by pheller** [clicon/clixon-controller#28] opened 2023-08-16 02:31 UTC
```
nobody@ddf1d696b811> show devices detail
<devices xmlns="http://clicon.org/controller">
   <device-timeout>60</device-timeout>
   <device>
      <name>r1</name>
      <enabled>true</enabled>
      <conn-type>NETCONF_SSH</conn-type>
      <user>noc</user>
      <addr>r1</addr>
      <yang-config>BIND</yang-config>
      <conn-state>OPEN</conn-state>
      <capabilities>
         <capability>urn:ietf:params:netconf:base:1.0</capability>
         <capability>urn:ietf:params:netconf:base:1.1</capability>
         <capability>urn:ietf:params:netconf:capability:candidate:1.0</capability>
         <capability>urn:ietf:params:netconf:capability:notification:1.0</capability>
         <capability>urn:ietf:params:netconf:capability:startup:1.0</capability>
         <capability>urn:ietf:params:netconf:capability:validate:1.1</capability>
         <capability>urn:ietf:params:netconf:capability:with-defaults:1.0?basic-mode=explicit&amp;also-supported=report-all,trim,report-all-tagged</capability>
         <capability>urn:ietf:params:netconf:capability:xpath:1.0</capability>
         <capability>urn:ietf:params:netconf:capability:yang-library:1.0?revision=2019-01-04&amp;module-set-id=0</capability>
         <capability>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</capability>
      </capabilities>
      <conn-state-timestamp>2023-08-16T02:25:03.386915Z</conn-state-timestamp>
      <sync-timestamp>2023-08-16T02:25:03.386622Z</sync-timestamp>
      <config>
         <restconf xmlns="http://clicon.org/restconf">
            <enable>true</enable>
            <auth-type>none</auth-type>
            <debug>0</debug>
            <log-destination>file</log-destination>
            <enable-core-dump>false</enable-core-dump>
            <pretty>false</pretty>
            <socket>
               <namespace>default</namespace>
               <address>0.0.0.0</address>
               <port>80</port>
               <ssl>false</ssl>
            </socket>
         </restconf>
         <yang-library xmlns="urn:ietf:params:xml:ns:yang:ietf-yang-library">
            <module-set>
               <name>mount</name>
               <module>
                  <name>clixon-lib</name>
                  <revision>2023-05-01</revision>
                  <namespace>http://clicon.org/lib</namespace>
               </module>
               <module>
                  <name>clixon-restconf</name>
                  <revision>2022-08-01</revision>
                  <namespace>http://clicon.org/restconf</namespace>
               </module>
               <module>
                  <name>iana-if-type</name>
                  <revision>2023-01-26</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:iana-if-type</namespace>
               </module>
               <module>
                  <name>ietf-datastores</name>
                  <revision>2018-02-14</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-datastores</namespace>
               </module>
               <module>
                  <name>ietf-inet-types</name>
                  <revision>2021-02-22</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-inet-types</namespace>
               </module>
               <module>
                  <name>ietf-interfaces</name>
                  <revision>2018-02-20</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-interfaces</namespace>
               </module>
               <module>
                  <name>ietf-list-pagination</name>
                  <revision>2022-07-24</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-list-pagination</namespace>
               </module>
               <module>
                  <name>ietf-list-pagination-nc</name>
                  <revision>2022-07-24</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-list-pagination-nc</namespace>
               </module>
               <module>
                  <name>ietf-netconf</name>
                  <revision>2011-06-01</revision>
                  <namespace>urn:ietf:params:xml:ns:netconf:base:1.0</namespace>
               </module>
               <module>
                  <name>ietf-netconf-monitoring</name>
                  <revision>2010-10-04</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring</namespace>
               </module>
               <module>
                  <name>ietf-netconf-nmda</name>
                  <revision>2019-01-07</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-nmda</namespace>
               </module>
               <module>
                  <name>ietf-netconf-with-defaults</name>
                  <revision>2011-06-01</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-netconf-with-defaults</namespace>
               </module>
               <module>
                  <name>ietf-origin</name>
                  <revision>2018-02-14</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-origin</namespace>
               </module>
               <module>
                  <name>ietf-restconf</name>
                  <revision>2017-01-26</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-restconf</namespace>
               </module>
               <module>
                  <name>ietf-yang-library</name>
                  <revision>2019-01-04</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-library</namespace>
               </module>
               <module>
                  <name>ietf-yang-metadata</name>
                  <revision>2016-08-05</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-metadata</namespace>
               </module>
               <module>
                  <name>ietf-yang-types</name>
                  <revision>2013-07-15</revision>
                  <namespace>urn:ietf:params:xml:ns:yang:ietf-yang-types</namespace>
               </module>
               <module>
                  <name>openconfig-aaa</name>
                  <revision>2022-07-29</revision>
                  <namespace>http://openconfig.net/yang/aaa</namespace>
               </module>
               <module>
                  <name>openconfig-aaa-radius</name>
                  <revision>2022-07-29</revision>
                  <namespace>http://openconfig.net/yang/aaa</namespace>
               </module>
               <module>
                  <name>openconfig-aaa-tacacs</name>
                  <revision>2022-07-29</revision>
                  <namespace>http://openconfig.net/yang/aaa</namespace>
               </module>
               <module>
                  <name>openconfig-aaa-types</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/aaa/types</namespace>
               </module>
               <module>
                  <name>openconfig-acl</name>
                  <revision>2023-02-06</revision>
                  <namespace>http://openconfig.net/yang/acl</namespace>
               </module>
               <module>
                  <name>openconfig-aft</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-common</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-ethernet</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-ipv4</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-ipv6</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-mpls</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-pf</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-state-synced</name>
                  <revision>2023-04-19</revision>
                  <namespace>http://openconfig.net/yang/aft</namespace>
               </module>
               <module>
                  <name>openconfig-aft-types</name>
                  <revision>2022-05-05</revision>
                  <namespace>http://openconfig.net/yang/fib-types</namespace>
               </module>
               <module>
                  <name>openconfig-alarm-types</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/alarms/types</namespace>
               </module>
               <module>
                  <name>openconfig-alarms</name>
                  <revision>2019-07-09</revision>
                  <namespace>http://openconfig.net/yang/alarms</namespace>
               </module>
               <module>
                  <name>openconfig-bfd</name>
                  <revision>2023-02-06</revision>
                  <namespace>http://openconfig.net/yang/bfd</namespace>
               </module>
               <module>
                  <name>openconfig-bgp</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-common</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-common-multiprotocol</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-common-structure</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-errors</name>
                  <revision>2023-03-31</revision>
                  <namespace>http://openconfig.net/yang/bgp-types</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-global</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-neighbor</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-peer-group</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-bgp-types</name>
                  <revision>2023-03-31</revision>
                  <namespace>http://openconfig.net/yang/bgp-types</namespace>
               </module>
               <module>
                  <name>openconfig-defined-sets</name>
                  <revision>2022-12-14</revision>
                  <namespace>http://openconfig.net/yang/defined-sets</namespace>
               </module>
               <module>
                  <name>openconfig-evpn</name>
                  <revision>2023-07-12</revision>
                  <namespace>http://openconfig.net/yang/evpn</namespace>
               </module>
               <module>
                  <name>openconfig-evpn-types</name>
                  <revision>2021-06-21</revision>
                  <namespace>http://openconfig.net/yang/evpn-types</namespace>
               </module>
               <module>
                  <name>openconfig-extensions</name>
                  <revision>2022-10-05</revision>
                  <namespace>http://openconfig.net/yang/openconfig-ext</namespace>
               </module>
               <module>
                  <name>openconfig-icmpv4-types</name>
                  <revision>2023-01-26</revision>
                  <namespace>http://openconfig.net/yang/openconfig-icmpv4-types</namespace>
               </module>
               <module>
                  <name>openconfig-icmpv6-types</name>
                  <revision>2023-05-02</revision>
                  <namespace>http://openconfig.net/yang/openconfig-icmpv6-types</namespace>
               </module>
               <module>
                  <name>openconfig-if-aggregate</name>
                  <revision>2022-06-28</revision>
                  <namespace>http://openconfig.net/yang/interfaces/aggregate</namespace>
               </module>
               <module>
                  <name>openconfig-if-ethernet</name>
                  <revision>2023-03-10</revision>
                  <namespace>http://openconfig.net/yang/interfaces/ethernet</namespace>
               </module>
               <module>
                  <name>openconfig-igmp</name>
                  <revision>2023-02-03</revision>
                  <namespace>http://openconfig.net/yang/igmp</namespace>
               </module>
               <module>
                  <name>openconfig-igmp-types</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/igmp/types</namespace>
               </module>
               <module>
                  <name>openconfig-inet-types</name>
                  <revision>2023-02-06</revision>
                  <namespace>http://openconfig.net/yang/types/inet</namespace>
               </module>
               <module>
                  <name>openconfig-interfaces</name>
                  <revision>2023-07-14</revision>
                  <namespace>http://openconfig.net/yang/interfaces</namespace>
               </module>
               <module>
                  <name>openconfig-isis</name>
                  <revision>2023-05-01</revision>
                  <namespace>http://openconfig.net/yang/openconfig-isis</namespace>
               </module>
               <module>
                  <name>openconfig-isis-lsdb-types</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/isis-lsdb-types</namespace>
               </module>
               <module>
                  <name>openconfig-isis-lsp</name>
                  <revision>2023-05-01</revision>
                  <namespace>http://openconfig.net/yang/openconfig-isis</namespace>
               </module>
               <module>
                  <name>openconfig-isis-routing</name>
                  <revision>2023-05-01</revision>
                  <namespace>http://openconfig.net/yang/openconfig-isis</namespace>
               </module>
               <module>
                  <name>openconfig-isis-types</name>
                  <revision>2022-02-11</revision>
                  <namespace>http://openconfig.net/yang/isis-types</namespace>
               </module>
               <module>
                  <name>openconfig-keychain</name>
                  <revision>2022-11-05</revision>
                  <namespace>http://openconfig.net/yang/oc-keychain</namespace>
               </module>
               <module>
                  <name>openconfig-keychain-types</name>
                  <revision>2022-03-01</revision>
                  <namespace>http://openconfig.net/yang/oc-keychain-types</namespace>
               </module>
               <module>
                  <name>openconfig-license</name>
                  <revision>2020-04-22</revision>
                  <namespace>http://openconfig.net/yang/license</namespace>
               </module>
               <module>
                  <name>openconfig-local-routing</name>
                  <revision>2022-11-01</revision>
                  <namespace>http://openconfig.net/yang/local-routing</namespace>
               </module>
               <module>
                  <name>openconfig-messages</name>
                  <revision>2018-08-13</revision>
                  <namespace>http://openconfig.net/yang/messages</namespace>
               </module>
               <module>
                  <name>openconfig-mpls</name>
                  <revision>2023-04-28</revision>
                  <namespace>http://openconfig.net/yang/mpls</namespace>
               </module>
               <module>
                  <name>openconfig-mpls-igp</name>
                  <revision>2023-04-28</revision>
                  <namespace>http://openconfig.net/yang/mpls</namespace>
               </module>
               <module>
                  <name>openconfig-mpls-ldp</name>
                  <revision>2023-02-06</revision>
                  <namespace>http://openconfig.net/yang/ldp</namespace>
               </module>
               <module>
                  <name>openconfig-mpls-rsvp</name>
                  <revision>2023-02-06</revision>
                  <namespace>http://openconfig.net/yang/rsvp</namespace>
               </module>
               <module>
                  <name>openconfig-mpls-sr</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/mpls-sr</namespace>
               </module>
               <module>
                  <name>openconfig-mpls-static</name>
                  <revision>2023-04-28</revision>
                  <namespace>http://openconfig.net/yang/mpls</namespace>
               </module>
               <module>
                  <name>openconfig-mpls-te</name>
                  <revision>2023-04-28</revision>
                  <namespace>http://openconfig.net/yang/mpls</namespace>
               </module>
               <module>
                  <name>openconfig-mpls-types</name>
                  <revision>2021-12-01</revision>
                  <namespace>http://openconfig.net/yang/mpls-types</namespace>
               </module>
               <module>
                  <name>openconfig-network-instance</name>
                  <revision>2023-07-12</revision>
                  <namespace>http://openconfig.net/yang/network-instance</namespace>
               </module>
               <module>
                  <name>openconfig-network-instance-l2</name>
                  <revision>2023-07-12</revision>
                  <namespace>http://openconfig.net/yang/network-instance</namespace>
               </module>
               <module>
                  <name>openconfig-network-instance-l3</name>
                  <revision>2022-11-08</revision>
                  <namespace>http://openconfig.net/yang/network-instance-l3</namespace>
               </module>
               <module>
                  <name>openconfig-network-instance-types</name>
                  <revision>2021-07-14</revision>
                  <namespace>http://openconfig.net/yang/network-instance-types</namespace>
               </module>
               <module>
                  <name>openconfig-ospf-types</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/ospf-types</namespace>
               </module>
               <module>
                  <name>openconfig-ospfv2</name>
                  <revision>2023-07-05</revision>
                  <namespace>http://openconfig.net/yang/ospfv2</namespace>
               </module>
               <module>
                  <name>openconfig-ospfv2-area</name>
                  <revision>2023-07-05</revision>
                  <namespace>http://openconfig.net/yang/ospfv2</namespace>
               </module>
               <module>
                  <name>openconfig-ospfv2-area-interface</name>
                  <revision>2023-07-05</revision>
                  <namespace>http://openconfig.net/yang/ospfv2</namespace>
               </module>
               <module>
                  <name>openconfig-ospfv2-common</name>
                  <revision>2023-07-05</revision>
                  <namespace>http://openconfig.net/yang/ospfv2</namespace>
               </module>
               <module>
                  <name>openconfig-ospfv2-global</name>
                  <revision>2023-07-05</revision>
                  <namespace>http://openconfig.net/yang/ospfv2</namespace>
               </module>
               <module>
                  <name>openconfig-ospfv2-lsdb</name>
                  <revision>2023-07-05</revision>
                  <namespace>http://openconfig.net/yang/ospfv2</namespace>
               </module>
               <module>
                  <name>openconfig-packet-match</name>
                  <revision>2023-03-01</revision>
                  <namespace>http://openconfig.net/yang/header-fields</namespace>
               </module>
               <module>
                  <name>openconfig-packet-match-types</name>
                  <revision>2023-01-29</revision>
                  <namespace>http://openconfig.net/yang/packet-match-types</namespace>
               </module>
               <module>
                  <name>openconfig-pcep</name>
                  <revision>2023-04-25</revision>
                  <namespace>http://openconfig.net/yang/pcep</namespace>
               </module>
               <module>
                  <name>openconfig-pf-forwarding-policies</name>
                  <revision>2023-04-25</revision>
                  <namespace>http://openconfig.net/yang/policy-forwarding</namespace>
               </module>
               <module>
                  <name>openconfig-pf-interfaces</name>
                  <revision>2023-04-25</revision>
                  <namespace>http://openconfig.net/yang/policy-forwarding</namespace>
               </module>
               <module>
                  <name>openconfig-pf-path-groups</name>
                  <revision>2023-04-25</revision>
                  <namespace>http://openconfig.net/yang/policy-forwarding</namespace>
               </module>
               <module>
                  <name>openconfig-pim</name>
                  <revision>2023-03-06</revision>
                  <namespace>http://openconfig.net/yang/pim</namespace>
               </module>
               <module>
                  <name>openconfig-pim-types</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/pim/types</namespace>
               </module>
               <module>
                  <name>openconfig-platform</name>
                  <revision>2023-02-13</revision>
                  <namespace>http://openconfig.net/yang/platform</namespace>
               </module>
               <module>
                  <name>openconfig-platform-common</name>
                  <revision>2023-02-13</revision>
                  <namespace>http://openconfig.net/yang/platform</namespace>
               </module>
               <module>
                  <name>openconfig-platform-types</name>
                  <revision>2023-06-27</revision>
                  <namespace>http://openconfig.net/yang/platform-types</namespace>
               </module>
               <module>
                  <name>openconfig-policy-forwarding</name>
                  <revision>2023-04-25</revision>
                  <namespace>http://openconfig.net/yang/policy-forwarding</namespace>
               </module>
               <module>
                  <name>openconfig-policy-types</name>
                  <revision>2022-11-08</revision>
                  <namespace>http://openconfig.net/yang/policy-types</namespace>
               </module>
               <module>
                  <name>openconfig-procmon</name>
                  <revision>2019-03-15</revision>
                  <namespace>http://openconfig.net/yang/system/procmon</namespace>
               </module>
               <module>
                  <name>openconfig-rib-bgp</name>
                  <revision>2022-12-20</revision>
                  <namespace>http://openconfig.net/yang/rib/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-rib-bgp-attributes</name>
                  <revision>2022-12-20</revision>
                  <namespace>http://openconfig.net/yang/rib/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-rib-bgp-shared-attributes</name>
                  <revision>2022-12-20</revision>
                  <namespace>http://openconfig.net/yang/rib/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-rib-bgp-table-attributes</name>
                  <revision>2022-12-20</revision>
                  <namespace>http://openconfig.net/yang/rib/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-rib-bgp-tables</name>
                  <revision>2022-12-20</revision>
                  <namespace>http://openconfig.net/yang/rib/bgp</namespace>
               </module>
               <module>
                  <name>openconfig-rib-bgp-types</name>
                  <revision>2019-03-14</revision>
                  <namespace>http://openconfig.net/yang/rib/bgp-types</namespace>
               </module>
               <module>
                  <name>openconfig-routing-policy</name>
                  <revision>2022-05-24</revision>
                  <namespace>http://openconfig.net/yang/routing-policy</namespace>
               </module>
               <module>
                  <name>openconfig-segment-routing</name>
                  <revision>2023-05-24</revision>
                  <namespace>http://openconfig.net/yang/sr</namespace>
               </module>
               <module>
                  <name>openconfig-segment-routing-types</name>
                  <revision>2020-02-04</revision>
                  <namespace>http://openconfig.net/yang/segment-routing-types</namespace>
               </module>
               <module>
                  <name>openconfig-srte-policy</name>
                  <revision>2021-07-28</revision>
                  <namespace>http://openconfig.net/yang/segment-routing/srte-policy</namespace>
               </module>
               <module>
                  <name>openconfig-system</name>
                  <revision>2023-06-16</revision>
                  <namespace>http://openconfig.net/yang/system</namespace>
               </module>
               <module>
                  <name>openconfig-system-logging</name>
                  <revision>2023-05-04</revision>
                  <namespace>http://openconfig.net/yang/system/logging</namespace>
               </module>
               <module>
                  <name>openconfig-system-terminal</name>
                  <revision>2018-11-21</revision>
                  <namespace>http://openconfig.net/yang/system/terminal</namespace>
               </module>
               <module>
                  <name>openconfig-transport-types</name>
                  <revision>2023-08-03</revision>
                  <namespace>http://openconfig.net/yang/transport-types</namespace>
               </module>
               <module>
                  <name>openconfig-types</name>
                  <revision>2019-04-16</revision>
                  <namespace>http://openconfig.net/yang/openconfig-types</namespace>
               </module>
               <module>
                  <name>openconfig-vlan</name>
                  <revision>2023-02-07</revision>
                  <namespace>http://openconfig.net/yang/vlan</namespace>
               </module>
               <module>
                  <name>openconfig-vlan-types</name>
                  <revision>2022-05-24</revision>
                  <namespace>http://openconfig.net/yang/vlan-types</namespace>
               </module>
               <module>
                  <name>openconfig-yang-types</name>
                  <revision>2021-07-14</revision>
                  <namespace>http://openconfig.net/yang/types/yang</namespace>
               </module>
            </module-set>
         </yang-library>
      </config>
   </device>
</devices>
nobody@ddf1d696b811> configure
nobody@ddf1d696b811[device=r1/]# show
<name>r1</name>
<conn-type>NETCONF_SSH</conn-type>
<user>noc</user>
<addr>r1</addr>
<yang-config>BIND</yang-config>
<config>
   <restconf xmlns="http://clicon.org/restconf">
      <enable>true</enable>
      <auth-type>none</auth-type>
      <debug>0</debug>
      <log-destination>file</log-destination>
      <pretty>false</pretty>
      <socket>
         <namespace>default</namespace>
         <address>0.0.0.0</address>
         <port>80</port>
         <ssl>false</ssl>
      </socket>
   </restconf>
</config>
nobody@ddf1d696b811[device=r1/]# set config
Aug 16 02:25:54: xp_yang_op_eq: 122: Yang error: Invalid path-arg (Error in xy1 or xy2) : Invalid argument
CLI command error
nobody@ddf1d696b811[device=r1/]#
```

And, on the device itself:
```
openconfig> set system config hostname r1
openconfig> show configuration xml
<system xmlns="http://openconfig.net/yang/system">
   <config>
      <hostname>r1</hostname>
   </config>
</system>
<restconf xmlns="http://clicon.org/restconf">
   <enable>true</enable>
   <auth-type>none</auth-type>
   <debug>0</debug>
   <log-destination>file</log-destination>
   <pretty>false</pretty>
   <socket>
      <namespace>default</namespace>
      <address>0.0.0.0</address>
      <port>80</port>
      <ssl>false</ssl>
   </socket>
</restconf>
```

Back on the controller:
```
nobody@ddf1d696b811> show devices check
device out-of-sync
nobody@ddf1d696b811> pull r1
OK
nobody@ddf1d696b811> show devices check
OK
nobody@ddf1d696b811> show configuration devices device r1
r1:
<device>
   <name>r1</name>
   <conn-type>NETCONF_SSH</conn-type>
   <user>noc</user>
   <addr>r1</addr>
   <yang-config>BIND</yang-config>
   <config>
      <restconf xmlns="http://clicon.org/restconf">
         <enable>true</enable>
         <auth-type>none</auth-type>
         <debug>0</debug>
         <log-destination>file</log-destination>
         <pretty>false</pretty>
         <socket>
            <namespace>default</namespace>
            <address>0.0.0.0</address>
            <port>80</port>
            <ssl>false</ssl>
         </socket>
      </restconf>
      <system xmlns="http://openconfig.net/yang/system">
         <config>
            <hostname>r1</hostname>
         </config>
      </system>
   </config>
</device>
```

**Comment by krihal** [comment] 2023-08-17 07:39
Duplicate of #26.

**Closed** 2023-08-17 11:42 UTC
Labels: bug, duplicate
